// @generated by mei-codegen (coding) from https://models.dev/catalog.json — do not edit by hand.
use super::{Model, Provider};

pub(super) static PROVIDERS: &[Provider] = &[
    Provider {
        id: "anthropic",
        name: "Anthropic",
        base_url: "https://api.anthropic.com",
        env: &["ANTHROPIC_API_KEY"],
    },
    Provider {
        id: "openai",
        name: "OpenAI",
        base_url: "https://api.openai.com/v1",
        env: &["OPENAI_API_KEY"],
    },
    Provider {
        id: "google",
        name: "Google",
        base_url: "https://generativelanguage.googleapis.com/v1beta",
        env: &[
            "GOOGLE_API_KEY",
            "GOOGLE_GENERATIVE_AI_API_KEY",
            "GEMINI_API_KEY",
        ],
    },
];

pub(super) static MODELS: &[Model] = &[
    Model {
        provider: "anthropic",
        id: "claude-fable-5",
        name: "Claude Fable 5",
        context: 1000000,
        max_output: 128000,
    },
    Model {
        provider: "anthropic",
        id: "claude-haiku-4-5",
        name: "Claude Haiku 4.5",
        context: 200000,
        max_output: 64000,
    },
    Model {
        provider: "anthropic",
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        context: 1000000,
        max_output: 128000,
    },
    Model {
        provider: "anthropic",
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        context: 1000000,
        max_output: 64000,
    },
    Model {
        provider: "google",
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro Preview",
        context: 1048576,
        max_output: 65536,
    },
    Model {
        provider: "google",
        id: "gemini-3.5-flash",
        name: "Gemini 3.5 Flash",
        context: 1048576,
        max_output: 65536,
    },
    Model {
        provider: "openai",
        id: "gpt-5.3-codex-spark",
        name: "GPT-5.3 Codex Spark",
        context: 128000,
        max_output: 32000,
    },
    Model {
        provider: "openai",
        id: "gpt-5.4-mini",
        name: "GPT-5.4 mini",
        context: 400000,
        max_output: 128000,
    },
    Model {
        provider: "openai",
        id: "gpt-5.5",
        name: "GPT-5.5",
        context: 1050000,
        max_output: 128000,
    },
];
