// @generated by mei-codegen (image) from https://models.dev/catalog.json — do not edit by hand.
use super::{Model, Provider};

pub(super) static PROVIDERS: &[Provider] = &[
    Provider {
        id: "openai",
        name: "OpenAI",
        base_url: "https://api.openai.com/v1",
        env: &["OPENAI_API_KEY"],
    },
    Provider {
        id: "google",
        name: "Google",
        base_url: "https://generativelanguage.googleapis.com/v1beta",
        env: &[
            "GOOGLE_API_KEY",
            "GOOGLE_GENERATIVE_AI_API_KEY",
            "GEMINI_API_KEY",
        ],
    },
];

pub(super) static MODELS: &[Model] = &[
    Model {
        provider: "openai",
        id: "chatgpt-image-latest",
        name: "chatgpt-image-latest",
        context: 0,
        max_output: 0,
    },
    Model {
        provider: "openai",
        id: "gpt-image-1",
        name: "gpt-image-1",
        context: 0,
        max_output: 0,
    },
    Model {
        provider: "openai",
        id: "gpt-image-1-mini",
        name: "gpt-image-1-mini",
        context: 0,
        max_output: 0,
    },
    Model {
        provider: "openai",
        id: "gpt-image-1.5",
        name: "gpt-image-1.5",
        context: 0,
        max_output: 0,
    },
    Model {
        provider: "openai",
        id: "gpt-image-2",
        name: "gpt-image-2",
        context: 0,
        max_output: 0,
    },
    Model {
        provider: "google",
        id: "gemini-2.5-flash-image",
        name: "Nano Banana",
        context: 32768,
        max_output: 32768,
    },
    Model {
        provider: "google",
        id: "gemini-3-pro-image-preview",
        name: "Nano Banana Pro",
        context: 131072,
        max_output: 32768,
    },
    Model {
        provider: "google",
        id: "gemini-3.1-flash-image-preview",
        name: "Nano Banana 2",
        context: 65536,
        max_output: 65536,
    },
];
